### ISSUE TITLE
Include styles

### ISSUE THREAD

**Issue by candidodmv** [alexadam/save-as-ebook#1]
this is just a tip, for future releases.

**Comment by alexadam** [comment]
Thanks for the tip! I've added it on the to-do list and I'll close this issue when it's implemented.

**Comment by alexadam** [comment]
in the last version I added experimental support for styles (CSS). Can you try it and let me know how it works? There are also some predefined templates that you can apply to remove the 'useless' parts on some popular websites. Thanks!

**Comment by candidodmv** [comment]
Thanks, works so fine! did make me happy see that my suggestion was useful.
