### ISSUE TITLE
Handle consecutive line break (<br /> tag) as paragraphs

### ISSUE THREAD

**Issue by asifm91** [alexadam/save-as-ebook#17]
Some pages use double line breaks (&lt;br&gt;, &lt;br /&gt;) instead of paragraphs. During conversion, these tags are trimmed (I guess), which causes the whole book/chapter to be a single paragraph.

**Comment by alexadam** [comment]
I've just released a new version 1.2.1 that should fix this issue. Can you update and confirm, please?

**Comment by asifm91** [comment]
Fixed. v1.2.1 now preserves the tags properly.
