### ISSUE TITLE
where can I download the plugin?

### ISSUE THREAD

**Issue by Udo-nk** [alexadam/save-as-ebook#2]

**Comment by alexadam** [comment]
The extension/plugin is not yet published in the browsers' web stores. You can download it from the main page -> Clone or Download -> Download as ZIP (see the image below) & then follow 'how to install' instructions.

![hn6](https://cloud.githubusercontent.com/assets/1687725/17846264/2e5f7a0c-6850-11e6-90bb-0b0dab063849.png)
