### ISSUE TITLE
Latex formulas are huge 

### ISSUE THREAD

**Issue by user135711** [alexadam/save-as-ebook#26]
Latex formulas result in giant height and width images in the output epub. (For instance try to convert [this equation](https://en.wikipedia.org/wiki/Schr%C3%B6dinger_equation)). When I convert with dotepub they are slightly large but better.

**Comment by alexadam** [comment]
I just did a release with a fix for this. Can you, please, give it a try an let me know if it works? Thanks

**Comment by user135711** [comment]
Certainly!

**Comment by user135711** [comment]
It's better, if the comparison file that i have from last week is from your extension and not one of the others I tried.
![image](https://user-images.githubusercontent.com/31940582/42977484-56f6bb14-8b7c-11e8-92ca-191d80292b44.png)

 It still looks big in Calibre. I have tried several epub readers to determine whether the problem is with save as ebook or the reader and I have found that only calibre actually displays the latex equations.  After trying 5 or 6 windows epub readers, they display ascii versions or a blank space. Calibre on the other hand seems to convert epub format to a website so that the original mathjax appears to be rendering and then output as an image like on wikipedia. I estimate if you scale it down 50% more it will be right, but I don't know if that will adjust the line wraps so the equation fills the line before being rendered into and svg.

**Comment by bunglegrind** [comment]
I will give a try today or tomorrow, on my kobo aura one with koreader.

**Comment by bunglegrind** [comment]
Let's begin. Latex sample page:

https://www.tuhh.de/MathJax/test/sample-tex.html

Both in calibre and koreader all formulas are converted to null.

**Comment by user135711** [comment]
FYI, all the epub plugins I tested(dotEpub, EpubPress) seem to have the same bug on that example.

**Comment by bunglegrind** [comment]
> 
> 
> Let's begin. Latex sample page:
> 
> https://www.tuhh.de/MathJax/test/sample-tex.html
> 
> Both in calibre and koreader all formulas are converted to null.

Yep, now it's working (at least in the sample page). I'll try in a more challenging page.
Thanks!
