### ISSUE TITLE
Some of Save as Ebook's epubs are incompatible with Iriver Story Hd

### ISSUE THREAD

**Issue by MarjaE2** [alexadam/save-as-ebook#29]
For example, an epub generated from this page only gets the header and the last page:

http://regiment.ru/Lib/C/172.htm

Also the header and the text on the last page stretch off the right side of the screen.

Running through Calibre, and converting to mobi, the language support issues leave it unreadable on the Kindle 2, but show much more text there.

Running through Calibre, converting to mobi, and coverting back to epub gives 4 pages on the Story Hd, still missing most of the text, and still stretching off the right side.

**Comment by alexadam** [comment]
I cannot reproduce this issue with that link. I tried with both Chrome & Firefox and opened the resulting ebook with Calibre. Moreover I tested it with this epub validator http://validator.idpf.org/application/validate and it does not have any errors.

**Comment by MarjaE2** [comment]
Validator isn't detecting the bug here either.
