### ISSUE TITLE
syntax highlighted code rendering is messed up 

### ISSUE THREAD

**Issue by btbytes** [alexadam/save-as-ebook#3]
Please see the comparison between the HTML rendering of the code and its epub version obtained using save-as-ebook. The epub was opened using iBook.

<img width="206" alt="pgss 2016-08-24 at 9 06 37 am" src="https://cloud.githubusercontent.com/assets/1047/17931609/56738502-69da-11e6-9ea0-fea84fee556e.png">
<img width="133" alt="pgss 2016-08-24 at 9 06 24 am" src="https://cloud.githubusercontent.com/assets/1047/17931608/5671b4d4-69da-11e6-95b1-bfa10d566e98.png">

**Comment by alexadam** [comment]
Can you, please, send me a link with the example (or something similar)? Thanks.

**Comment by btbytes** [comment]
See how the syntax highlighted code renders on this page - https://www.btbytes.com/pages/org-simple.html

**Comment by alexadam** [comment]
I did some changes, it's far from perfect but I think it renders pre/code elements better now. Can you, please, update and retry? At this point styles are not supported so the syntax highlight is not preserved.
