### ISSUE TITLE
Firefox Add-on doesn't finish installing 

### ISSUE THREAD

**Issue by lazysoundsystem** [alexadam/save-as-ebook#4]
No idea what the problem is, but just to let you know I've tried to install as a Firefox add-on a number of times without success. 

Clicking 'Add to Firefox' on https://addons.mozilla.org/en-US/firefox/addon/saveasebook/ opens a dialogue that shows it downloads fully very quickly but doesn't seem to install.

On 'about:addons' it shows as 'Downloading' but doesn't complete and can't be cancelled without closing the browser completely.

The manual install works fine.

(Really useful add-on - thanks!)

**Comment by alexadam** [comment]
Hmm... I'll take a look on it. Maybe it's because the extension is not compatible with the latest stable Firefox.

**Comment by lazysoundsystem** [comment]
Thanks!
 
Web extensions should make things easier in the future: https://developer.mozilla.org/en-US/Add-ons
and there's help with migrating addons here: https://compatibility-lookup.services.mozilla.com/
