### ISSUE TITLE
Chapter Queue should not auto-clear, to give user opportunity to make edits.

### ISSUE THREAD

**Issue by davidvb** [alexadam/save-as-ebook#6]
Today I wasted an hour trying to make a large ePub from 25+ favourite Medium.com articles on UX design.
Once I was done adding chapters I rendered the ePub. 

It downloaded the hefty 114Mb ePub and cleared the Chapter Queue, yet the generated ePub wouldn't successfully open, and triggered a "corrupt!" warning in iBooks.
I tried converting it to a PDF with online tools but they all say the filesize is too big.

To improve the overal experience, consider adding Projects/sessions the user can come back to, save mid-session, or edit/add content to at later time.
Alternatively it would also be an improvement if the "project" would at least get saved locally, so that a refresh (accidental, forced or intentional) won't mean losing your progress.

**Comment by alexadam** [comment]
Hi, I've just added an option to save the changes in chapter editor. Also, after generating the eBook, the chapters will not be cleared. All changes are persisted in browser's storage so they are available  even after restart. I didn't publish to the chrome & ff stores yet. If you want, you can install it manually and give it a try... 
Can you send me those links which generated a 100 mb ebook? I want to make some tests. Thanks.

**Comment by alexadam** [comment]
Adding Projects/Session is a nice idea but it's not a priority for now (added on the to-do list). The next major update will support custom css styles & templates. And the next one, hopefully, an option to save as audiobook. Feedback & ideas are welcome!
