### ISSUE TITLE
Change destination folder ?

### ISSUE THREAD

**Issue by rakoo** [alexadam/save-as-ebook#69]
Hey, thanks a lot for this amazing extension ! It has become a mandatory part of my workflow now.

However to make it even better I'd like to save all epubs to a folder of my choosing. Basically it's a folder shared on syncthing, and I use that folder to automagically transfer stuff to read to my phone and have it available on the go. I don't want to share the whole Downloads folder, so instead I put all epubs in there but it's a tedious, manual operation. Saving epubs directly in my shared folder would be amazing.

**Comment by alexadam** [comment]
Hi, thanks for the comment!

Isn't this a problem that can be solved with the browser, by selecting a specific folder to download the ebook? A web-extension cannot control where a file is saved on the disk.

**Comment by rakoo** [comment]
Yes and no: the `Downloads` setting is global, and is set both for standard click-on-a-link and for extensions. There's no way to set a different setting per extension, AFAIK.

I see there's [this extension](https://addons.mozilla.org/en-US/firefox/addon/quick-sorted-download/) allowing you to specify a specific *subfolder* of the global setting, but that's still not aligned with what I want to do.

For the moment I hacked up some systemd service to automatically move .epub files to my shared folder, it works but I wish it were all self-contained in the extension. However if you tell me it can't be done, then I'll be closing this issue :)

**Comment by alexadam** [comment]
@rakoo do you think save-as-ebook would be more useful as a separate, stand alone app? I didn't have time to add more features to the web extension... and there are also a lot of limitations. Recreating it as a stand alone app would make it more powerful and flexible but less accessible for common users.

**Comment by rakoo** [comment]
I don't think it would be particularly better, especially considering the additional complexity. I feel like save-as-ebook can do the web->epub file and additional functionalities are best handled by orthogonal applications, but I may be biased
